### ISSUE TITLE
Update the message displayed by chatbot for sample questions

### ISSUE THREAD

**Issue by Kanchan23** [PaytmBuildForIndia/book-engine#15]
If the bot does not understand any message, it says “Sorry, an error occurred. Please try again or contact at @mukul1904. You can also say 'help' to get sample questions to ask."

Instead it can say “Can’t understand this message. Please try again or type ‘help’ to get sample questions to ask."

**Comment by myke11j** [comment]
Done

**Comment by Kanchan23** [comment]
Verified
